# .pre-commit-hooks.yaml
      - --all-files
      - ./.mobile-security.yaml
      - --config
      - run
    args:
    files: '.*'
    language: python
    entry: pre-commit
    name: Security Profile - Mobile
-   id: security-profile-mobile

      - --all-files
      - ./.infra-security.yaml
      - --config
      - run
    args:
    files: '.*'
    language: python
    entry: pre-commit
    name: Security Profile - Infrastructure
-   id: security-profile-infra

      - --all-files
      - ./.web-app-security.yaml
      - --config
      - run
    args:
    files: '.*'
    language: python
    entry: pre-commit
    name: Security Profile - Web Application
-   id: security-profile-web-app

      - --all-files
      - ./.base-security.yaml
      - --config
      - run
    args:
    files: '.*'
    language: python
    entry: pre-commit
    name: Security Profile - Base
-   id: security-profile-base

# Managed exclusively by the AppSec Team
# Centralized AppSec Pre-Commit Hooks

