# .pre-commit-hooks.yaml
# Centralized AppSec Pre-Commit Hooks
# Managed exclusively by the AppSec Team

-   id: security-profile-base
    name: Security Profile - Base
    entry: pre-commit
    language: python
    files: '.*'
    args:
      - run
      - --config
      - ./.base-security.yaml
      - --all-files

-   id: security-profile-web-app
    name: Security Profile - Web Application
    entry: pre-commit
    language: python
    files: '.*'
    args:
      - run
      - --config
      - ./.web-app-security.yaml
      - --all-files

-   id: security-profile-infra
    name: Security Profile - Infrastructure
    entry: pre-commit
    language: python
    files: '.*'
    args:
      - run
      - --config
      - ./.infra-security.yaml
      - --all-files

-   id: security-profile-mobile
    name: Security Profile - Mobile
    entry: pre-commit
    language: python
    files: '.*'
    args:
      - run
      - --config
      - ./.mobile-security.yaml
      - --all-files