-   id: gitleaks
    name: Gitleaks
    description: "Scans for hardcoded secrets"
    entry: gitleaks protect --staged --verbose
    language: golang
    types: [text]

-   id: semgrep-sast
    name: Semgrep SAST
    description: "Static analysis for security vulnerabilities"
    entry: semgrep --config=auto --error
    language: python
    types: [python]
    require_serial: true

-   id: checkov-iac
    name: Checkov IaC
    description: "Scans infrastructure as code for misconfigurations"
    entry: checkov -f
    language: python
    types: [terraform]

-   id: corporate-security-critical
    name: Corporate Security Critical
    description: "Runs all critical security checks"
    entry: bash -c 'pre-commit run gitleaks && pre-commit run semgrep-sast'
    language: system
    pass_filenames: false
    always_run: true