-   id: gitleaks
    name: Gitleaks
    description: "Scans for hardcoded secrets"
    entry: gitleaks detect --source . --report-path /dev/stdout --verbose
    language: docker_image
    image: zricethezav/gitleaks:latest

-   id: semgrep-sast
    name: Semgrep SAST
    description: "Static analysis for security vulnerabilities"
    entry: semgrep --config=auto --error
    language: docker_image
    image: semgrep/semgrep

-   id: checkov-iac
    name: Checkov IaC
    description: "Scans infrastructure as code for misconfigurations"
    entry: checkov --directory .
    language: docker_image
    image: bridgecrew/checkov:latest

-   id: corporate-security-critical
    name: Corporate Security Critical
    description: "Runs all critical security checks"
    entry: bash -c 'pre-commit run gitleaks && pre-commit run semgrep-sast'
    language: system
    pass_filenames: false
    always_run: true

