-   id: gitleaks-system
    name: Detect hardcoded secrets
    description: Detect hardcoded secrets using Gitleaks
    entry: gitleaks git --pre-commit --redact --staged --verbose
    language: system

-   id: semgrep-sast
    name: Semgrep SAST
    description: "Static analysis for security vulnerabilities"
    entry: semgrep --config=auto --error
    language: system
    image: semgrep/semgrep

-   id: checkov-iac
    name: Checkov IaC
    description: "Scans infrastructure as code for misconfigurations"
    entry: checkov --directory .
    language: system
    image: bridgecrew/checkov:latest

-   id: corporate-security-critical
    name: Corporate Security Critical
    description: "Runs all critical security checks"
    entry: bash -c 'pre-commit run gitleaks && pre-commit run semgrep-sast'
    language: system
    pass_filenames: false
    always_run: true

