#!/bin/bash
# install.sh - AppSec Hooks Installation Script
# Usage: curl -sSL https://raw.githubusercontent.com/ihrishikesh0896/appsec-hooks/main/install.sh | bash

set -e

APPSEC_REPO="https://github.com/ihrishikesh0896/appsec-hooks"
LATEST_VERSION="v1.0.0"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_banner() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║     AppSec Pre-Commit Hook Installer     ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
    echo ""
}

check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"

    # Check if we're in a git repository
    if ! git rev-parse --is-inside-work-tree &> /dev/null; then
        echo -e "${RED}Error: Not inside a git repository${NC}"
        echo "Please run this script from the root of your git repository."
        exit 1
    fi

    if ! command -v git &> /dev/null; then
        echo -e "${RED}Error: git is not installed${NC}"
        exit 1
    fi

    if ! command -v pre-commit &> /dev/null; then
        echo -e "${YELLOW}pre-commit not found. Installing...${NC}"
        if command -v pip &> /dev/null; then
            pip install pre-commit
        elif command -v pip3 &> /dev/null; then
            pip3 install pre-commit
        elif command -v brew &> /dev/null; then
            brew install pre-commit
        else
            echo -e "${RED}Error: Cannot install pre-commit. Please install pip or brew first.${NC}"
            exit 1
        fi
    fi

    echo -e "${GREEN}✓ All prerequisites met${NC}"
}

select_profile() {
    echo ""
    echo "Select your security profile:"
    echo ""
    echo "  1) Base       - Minimal security (secrets, basic checks)"
    echo "  2) Web App    - Web applications (OWASP, XSS, SQLi, dependency scanning)"
    echo "  3) Infra      - Infrastructure-as-Code (Terraform, Kubernetes, CloudFormation)"
    echo "  4) Mobile     - Mobile applications (iOS, Android, MobSF rules)"
    echo ""
    read -p "Enter choice [1-4]: " choice

    case $choice in
        1)
            PROFILE="security-profile-base"
            PROFILE_DESC="Base"
            ;;
        2)
            PROFILE="security-profile-web-app"
            PROFILE_DESC="Web Application"
            ;;
        3)
            PROFILE="security-profile-infra"
            PROFILE_DESC="Infrastructure"
            ;;
        4)
            PROFILE="security-profile-mobile"
            PROFILE_DESC="Mobile"
            ;;
        *)
            echo -e "${RED}Invalid choice. Please enter 1-4.${NC}"
            exit 1
            ;;
    esac

    echo -e "${GREEN}✓ Selected profile: ${PROFILE_DESC}${NC}"
}

create_config() {
    CONFIG_FILE=".pre-commit-config.yaml"

    if [ -f "$CONFIG_FILE" ]; then
        echo -e "${YELLOW}Existing ${CONFIG_FILE} found.${NC}"
        read -p "Backup and replace? [y/N]: " backup
        if [[ $backup =~ ^[Yy]$ ]]; then
            BACKUP_FILE="${CONFIG_FILE}.backup.$(date +%s)"
            mv "$CONFIG_FILE" "$BACKUP_FILE"
            echo -e "${GREEN}✓ Backup created: ${BACKUP_FILE}${NC}"
        else
            echo -e "${YELLOW}Appending to existing config...${NC}"
            echo "" >> "$CONFIG_FILE"
            echo "  # AppSec Security Baseline - ${PROFILE_DESC}" >> "$CONFIG_FILE"
            echo "  - repo: ${APPSEC_REPO}" >> "$CONFIG_FILE"
            echo "    rev: ${LATEST_VERSION}" >> "$CONFIG_FILE"
            echo "    hooks:" >> "$CONFIG_FILE"
            echo "      - id: ${PROFILE}" >> "$CONFIG_FILE"
            echo -e "${GREEN}✓ AppSec hooks appended to config${NC}"
            return
        fi
    fi

    cat > "$CONFIG_FILE" << EOF
# Pre-commit configuration
# Generated by AppSec Hook Installer
# Profile: ${PROFILE_DESC}
# Generated: $(date -Iseconds)

repos:
  # ============================================
  # Corporate Security Baseline
  # Managed by AppSec Team - DO NOT MODIFY
  # ============================================
  - repo: ${APPSEC_REPO}
    rev: ${LATEST_VERSION}
    hooks:
      - id: ${PROFILE}

  # ============================================
  # Team-specific hooks (add your own below)
  # ============================================
  # Example:
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.3
  #   hooks:
  #     - id: prettier
  #
  # - repo: https://github.com/psf/black
  #   rev: 24.4.2
  #   hooks:
  #     - id: black
EOF

    echo -e "${GREEN}✓ Created ${CONFIG_FILE}${NC}"
}

install_hooks() {
    echo ""
    echo -e "${YELLOW}Installing pre-commit hooks...${NC}"
    pre-commit install
    pre-commit install --hook-type pre-push
    echo -e "${GREEN}✓ Hooks installed successfully${NC}"
}

run_initial_scan() {
    echo ""
    read -p "Run initial security scan? [Y/n]: " scan
    if [[ ! $scan =~ ^[Nn]$ ]]; then
        echo -e "${YELLOW}Running security scan (this may take a while on first run)...${NC}"
        echo ""
        pre-commit run --all-files || true
    fi
}

print_summary() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║         Installation Complete!           ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
    echo ""
    echo "Security hooks will now run automatically on every commit."
    echo ""
    echo -e "${BLUE}Profile:${NC} ${PROFILE_DESC}"
    echo ""
    echo -e "${BLUE}Useful commands:${NC}"
    echo "  pre-commit run --all-files    # Scan all files"
    echo "  pre-commit autoupdate         # Update hook versions"
    echo "  pre-commit run <hook-id>      # Run specific hook"
    echo ""
    echo -e "${BLUE}Need help?${NC}"
    echo "  Documentation: ${APPSEC_REPO}"
    echo "  Slack: #appsec-support"
    echo ""
}

# Main execution
main() {
    print_banner
    check_prerequisites
    select_profile
    create_config
    install_hooks
    run_initial_scan
    print_summary
}

main "$@"

